apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: default
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    name: prometheus
