apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: default
spec:
  type: NodePort
  selector:
    component: grafana
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
